[tools]
ruby = "3.4.4"

[env]
PADDLE_DATABASE_PASSWORD = "postgres"
SWEETDATE_API_KEY_ID = "99eccb44-2b95-489e-8445-99f47aa45262" 
SWEETDATE_API_SECRET = "7Xp6HIex5rcxRBELL9ZVhYVb_ZPQE_3lbxKweXpVJow"
SWEETDATE_PORT = "5050"
SWEETDATE_HOST = "localhost"