[tools]
ruby = "3.4.4"

[env]
PADDLE_DATABASE_PASSWORD = "postgres"
SWEETDATE_API_KEY_ID = "63f14215-12a7-4921-a603-76996707ef19" 
SWEETDATE_API_SECRET = "DqdoG121FA_jYNLvhcVGiYjVecL0t009e_hFv_TUsis"
SWEETDATE_PORT = "5050"
SWEETDATE_HOST = "localhost"